### PR TITLE
Add HelloWorld15 testcase to componnent annotations testcase

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/osgi/osgi/issues/637
See also https://github.com/osgi/osgi/issues/642

### CODE REVIEW

**Review by timothyjward — APPROVED** [review]

**Comment by laeubi** [comment]
Where can I see that the new testcase is picked up?

**Comment by timothyjward** [comment]
It's in the uploaded artifacts for the run:

https://github.com/osgi/osgi/actions/runs/7870019446/artifacts/1237911161

**Comment by laeubi** [comment]
And it is there ... so this looks good to me

grafik

**Comment by timothyjward** [comment]
Thank you for the contribution - it will be discussed (and probably merged) in the next specification call

**Pull request merged**
