### PR TITLE
Use ECF impl for RSA tests (version: 3.14.24)

### PR DESCRIPTION
**Pull request by scottslewis**
to run RSA/RS TCK Tests

cnf/ext/central.mvn - Latest versions of ECF bundles from Maven Central

cnf/repo/org.osgi.impl.service.remoteserviceadmin-8.0.0.lib - Use ECF
bundles for remoteservice admin impl

org.osgi.test.cases.remoteserviceadmin/bnd.bnd - properties changes for
ECF as impl under test

org.osgi.test.cases.remoteserviceadmin.secure/bnd.bnd - properties
changes for ECF as impl under test

org.osgi.test.cases.remoteservices/bnd.bnd - properties changes for ECF
as impl under test

Signed-off-by: Scott Lewis <scottslewis@gmail.com>

### CODE REVIEW

**Comment by scottslewis** [comment]
There was a typo in the modified bnd file that was preventing compile/build.   Fixed with commit.

**Comment by rotty3000** [comment]
I've made the build run, but could you squash your commits (and force push to your branch) in the end? thx :)

**Review by rotty3000 — APPROVED** [review]
LGTM

**Comment by rotty3000** [comment]
Hello @scottslewis Everything looks good. Nice work.

However, we are currently racing toward the final release of Compendium R8 and so since we now have a stable build we're just going to wait until after the release to merge.

Thank you for your contribution.

**Review by bjhargrave — APPROVED** [review]

**Comment by scottslewis** [comment]
Hi @rotty3000.   What's your current best guess about the Comp R8 release timing?

**Comment by bjhargrave** [comment]
I rebased on main and fixed some issues in the bnd files. Also removed no-longer used dependencies related to the Aries RSA impl. Thanks for all the work on this @scottslewis!

**Pull request merged**
