### PR TITLE
Design for Type Safe Events 1.1

### PR DESCRIPTION
**Pull request by timothyjward**
This PR includes API, specification and test updates for the Type Safe Events 1.1 specification

### CODE REVIEW

**Comment by timothyjward** [comment]
TODO - we should discuss whether Record types are permitted as events

**Comment by stbischof** [comment]
if wou want to handle Java 16 Records without relying on Java 16: (reflectiva Access) 
https://github.com/stbischof/osgi/commit/0818b5981ea37b8ff799dc2f6b9587e6e58b5515

**Comment by timothyjward** [comment]
This PR has been updated with the changes requested by @jjh-aicas 

I have a couple of open questions:

* Should the return value of `getMaximumEventStorage` be an `int` rather than a `long`?
* Are we happy to use `Map.Entry` for the history retention policy or should we make a type just to hold the two values?
* Does the API (minimum and maximum retention) meet all the requirements, especially the return value from `configureHistoryStorage`?
* Are the topic Predicate/test methods useful?

**Comment by stbischof** [comment]
for TCK we have to extend this.

https://github.com/osgi/osgi/tree/main/org.osgi.test.cases.typedevent

**Pull request merged**
